/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektszyfrowanie;

/**
 *
 * @author Dominika
 */
public class okno extends javax.swing.JFrame {

    static char[] tabWordKey;

    /**
     * Creates new form okno
     */
    public okno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        btnSzyfru = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chbCezar = new javax.swing.JCheckBox();
        chbVigner = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        btmDeszyfruj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAzaszyfrowane = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaTextdo = new javax.swing.JTextArea();
        tfPrzesuniecie = new javax.swing.JTextField();
        tfKlucz = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Podaj tekst");

        btnSzyfru.setText("Szyfruj");
        btnSzyfru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzyfruActionPerformed(evt);
            }
        });

        jLabel1.setText("Wybierz algorytm");

        chbCezar.setText("Szyfr Cezara");
        chbCezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCezarActionPerformed(evt);
            }
        });

        chbVigner.setText("Szyfr Vigenère'a");
        chbVigner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbVignerActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Szyfr Płotowy");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        btmDeszyfruj.setText("Deszyfruj");
        btmDeszyfruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmDeszyfrujActionPerformed(evt);
            }
        });

        TAzaszyfrowane.setColumns(20);
        TAzaszyfrowane.setRows(5);
        jScrollPane1.setViewportView(TAzaszyfrowane);

        TaTextdo.setColumns(20);
        TaTextdo.setRows(5);
        jScrollPane2.setViewportView(TaTextdo);

        tfPrzesuniecie.setText("3");
        tfPrzesuniecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrzesuniecieActionPerformed(evt);
            }
        });

        tfKlucz.setText("TAJNE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbCezar)
                            .addComponent(chbVigner)
                            .addComponent(jCheckBox3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(276, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tfPrzesuniecie, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tfKlucz, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btmDeszyfruj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSzyfru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSzyfru))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbCezar)
                            .addComponent(tfPrzesuniecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbVigner)
                            .addComponent(tfKlucz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addGap(73, 73, 73)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmDeszyfruj))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbCezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCezarActionPerformed
        if (chbCezar.isSelected()) {
            chbVigner.setSelected(false);
        }

    }//GEN-LAST:event_chbCezarActionPerformed

    private void chbVignerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbVignerActionPerformed
        if (chbVigner.isSelected()) {
            chbCezar.setSelected(false);
        }
    }//GEN-LAST:event_chbVignerActionPerformed

    private void btmDeszyfrujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmDeszyfrujActionPerformed

        String textSzyfr = TAzaszyfrowane.getText();
        char TablicaZSztfrem[];
        int wsp = Integer.valueOf(tfPrzesuniecie.getText());
        String CałyTekst = "";

        TablicaZSztfrem = textSzyfr.toCharArray();
        char[] tekstZaszyfrowany = new char[TablicaZSztfrem.length];
        String klucz = tfKlucz.getText();
        tabWordKey = klucz.toCharArray();

        if (chbCezar.isSelected()) {

            char g = '9';
            int d = g;// spacja ma  int 32
            System.out.println(d + " gvDFJ ");

            for (int i = 0; i < TablicaZSztfrem.length; i++) {
                //  System.out.println(TablicaZSztfrem[i]);
                int temp = Integer.valueOf(TablicaZSztfrem[i]);
                System.out.println(Integer.valueOf(TablicaZSztfrem[i]));
                if (temp >= 100 && temp <= 122) {
                    tekstZaszyfrowany[i] = (char) (temp - wsp % 25);  // małe literri od a do w

                }

                if (temp >= 97 && temp <= 99) {
                    System.out.println(temp + " too jest to ");
                    tekstZaszyfrowany[i] = (char) (temp + (20 + wsp) % 25);  //xyz
                }

                if (temp >= 51 && temp <= 57) {
                    tekstZaszyfrowany[i] = (char) (temp - wsp % 10);  // cyferki od 3 do 9
                    System.out.println((char) temp + " teges  -3");
                }

                if (temp >= 48 && temp <= 50) {

                    System.out.println((char) temp + " teges  -3");
                    tekstZaszyfrowany[i] = (char) (temp + (4 + wsp) % 10);  // cyferki 0,1,2 
                }
                if (temp >= 68 && temp <= 91) {
                    tekstZaszyfrowany[i] = (char) (temp - wsp % 25);  // A do WU
                }
                if (temp >= 65 && temp <= 67) {
                    tekstZaszyfrowany[i] = (char) (temp + (20 + wsp) % 25);  // XYZ
                    System.out.println((char) temp + " wat  -3");
                }

                CałyTekst = "";

                CałyTekst = CałyTekst + String.valueOf(tekstZaszyfrowany);

                TAzaszyfrowane.setText(CałyTekst);
            }
        }

        if (chbVigner.isSelected()) {
            CałyTekst = "";
            int teges;
            char[] odwroceny = new char[TablicaZSztfrem.length];
            for (int i = 0; i < TablicaZSztfrem.length; i++) {
                int a = 'A';//  65 109 duze . cyfry od 0 do 9 48 57
                int z = 'B'; // male literki 97 do 122
                int T = 'T';//  65 109 duze . cyfry od 0 do 9 48 57
                int A = 'A';
                String az = String.valueOf(z);
//TablicaZSztfrem[i]'A'
                teges = (26 - tabWordKey[i]) % 26 + 64;
                System.out.println("teges " + /*(char)*/ teges);
                odwroceny[i] = (char) teges;
                CałyTekst = CałyTekst + (char) (TablicaZSztfrem[i] + tabWordKey[i] - 64);
                System.out.println(CałyTekst);
            }
            for (int i = odwroceny.length, j = 0; i == 0; i--, j++) {
                CałyTekst = CałyTekst + odwroceny[i];
                System.out.println(CałyTekst);
            }
            TAzaszyfrowane.setText("");
            TAzaszyfrowane.setText(CałyTekst);

        }


    }//GEN-LAST:event_btmDeszyfrujActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnSzyfruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzyfruActionPerformed
        String wordKey = tfKlucz.getText();
        char[] tabWordKey = wordKey.toCharArray();

        int przesuniecie = Integer.valueOf(tfPrzesuniecie.getText());

        System.out.println(przesuniecie);
        if (chbVigner.isSelected()) {

            char ch;
            int il = 'Z' - 'A';

            char tabVignera[][] = new char[il + 1][il + 1];
            char tabABC[] = new char[il + 1];
            int k = 0;
            for (int i = 'A'; i <= 'Z'; i++) {
                tabABC[k] = (char) i;

                k++;
            }

            for (int j = 0; j <= il; j++) {
                int licznik = j;
                for (int l = 0; l <= il; l++) {
                    tabVignera[j][l] = tabABC[licznik];

                    if (licznik >= il) {
                        licznik = 0;
                    } else {
                        licznik++;
                    }

                    // System.out.print(tabVignera[j][l]);
                }
                System.out.println(" ");
            }

            String text = TaTextdo.getText().toUpperCase();
            char TablicaZTextem[];
            char g = '0';
            int d = g;// spacja ma  int 32
            // System.out.println(d + " ");
            TablicaZTextem = text.toCharArray();

            char[] tabAuxiliary = new char[TablicaZTextem.length];
            int iKey = 0;

            String CałyTekst = "";
            for (int i = 0; i < TablicaZTextem.length; i++) {
                if (TablicaZTextem[i] != 32) {
                    // System.out.println(TablicaZTextem[i]);
                    if (iKey == tabWordKey.length) {
                        iKey = 0;
                    }

                    tabAuxiliary[i] = tabWordKey[iKey];
                    //     System.out.println(tabWordKey[iKey]);

                    iKey++;

                    CałyTekst = CałyTekst + String.valueOf(tabVignera[TablicaZTextem[i] - 65][tabAuxiliary[i] - 65]);

                } else {
                    CałyTekst = CałyTekst + TablicaZTextem[i];
                }
            }
            TAzaszyfrowane.setText(CałyTekst);
        }

        if (chbCezar.isSelected()) {
            String text = TaTextdo.getText();
            char TablicaZTextem[];

            int a = '0';//  65 109 duze . cyfry od 0 do 9 48 57
            int z = 'Z'; // male literki 97 do 122

            String az = String.valueOf(z);

            TablicaZTextem = text.toCharArray();
            char[] tekstZaszyfrowany = new char[TablicaZTextem.length];
            for (int i = 0; i < TablicaZTextem.length; i++) {
                int temp = (int) TablicaZTextem[i];

                if (temp >= 120 && temp <= 122) {
                    tekstZaszyfrowany[i] = (char) (temp - (20 + przesuniecie) % 25);  // małe literri
                }
                if (temp >= 97 && temp <= 119) {

                    tekstZaszyfrowany[i] = (char) (temp + przesuniecie % 25);  //xyz
                }

                if (temp >= 38 && temp <= 54) {
                    tekstZaszyfrowany[i] = (char) (temp + przesuniecie % 10);  // cyferki od 1 do 7
                }

                if (temp >= 55 && temp <= 58) {

                    System.out.println(temp);
                    tekstZaszyfrowany[i] = (char) (temp - (4 + przesuniecie) % 10);  // cyferki 8,9 0 
                }
                if (temp >= 65 && temp <= 87) {
                    tekstZaszyfrowany[i] = (char) (temp + przesuniecie % 25);  // A do WU
                }
                if (temp >= 88 && temp <= 90) {
                    tekstZaszyfrowany[i] = (char) (temp - (20 + przesuniecie) % 25);  // XYZ
                }

//                if (temp >= 33 && temp <= 64) {
//                    tekstZaszyfrowany[i] = (char) (temp + 3 % 31);  // poprawić
//                }
                String CałyTekst = "";

                CałyTekst = CałyTekst + String.valueOf(tekstZaszyfrowany);

                TAzaszyfrowane.setText(CałyTekst);
            }
    }//GEN-LAST:event_btnSzyfruActionPerformed
    }
    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void tfPrzesuniecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrzesuniecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrzesuniecieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(okno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(okno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(okno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(okno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAzaszyfrowane;
    private javax.swing.JTextArea TaTextdo;
    private javax.swing.JButton btmDeszyfruj;
    private javax.swing.JButton btnSzyfru;
    private javax.swing.JCheckBox chbCezar;
    private javax.swing.JCheckBox chbVigner;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JTextField tfKlucz;
    private javax.swing.JTextField tfPrzesuniecie;
    // End of variables declaration//GEN-END:variables
}
